name: Economic Calendar Telegram Bot

on:
  schedule:
    # Sabah 09:00'da günlük özet (TR saati → UTC-3:00 farkıyla 06:00 UTC)
    - cron: '0 6 * * *'
    # Her 30 dakikada bir alerts kontrolü
    - cron: '*/30 * * * *'
  workflow_dispatch:  # manuel çalıştırma

jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [summary, alerts]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python send_calendar_bot.py ${{ matrix.mode }}
