name: Economic Calendar Telegram Bot

on:
  schedule:
    # TR 09:00 -> UTC 06:00  (günlük özet)
    - cron: "0 6 * * *"
    # her 30 dakikada bir uyarı kontrolü
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      run_summary:
        description: "Manual: summary çalışsın mı?"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
      run_alerts:
        description: "Manual: alerts çalışsın mı?"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
      force:
        description: "Sessiz saatleri yok say (summary/alerts için)"
        required: true
        default: "false"
        type: choice
        options: ["false","true"]

# alerts job'larında çakışmayı önle
concurrency:
  group: econ-calendar-alerts
  cancel-in-progress: true

jobs:
  # ----------------- GÜNLÜK ÖZET -----------------
  daily_summary:
    # schedule'da sadece 06:00 UTC tetiklerinde çalışsın;
    # manual'da run_summary=true ise çalışsın
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 6 * * *') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_summary == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send summary
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_RUN:          ${{ github.event.inputs.force }}
        run: |
          python send_calendar_bot.py summary

  # ----------------- 30 DK UYARILAR -----------------
  half_hour_alerts:
    # schedule'da sadece */30 tetiklerinde çalışsın;
    # manual'da run_alerts=true ise çalışsın
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '*/30 * * * *') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_alerts == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alerts (25–35 dk penceresi)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_RUN:          ${{ github.event.inputs.force }}
        run: |
          python send_calendar_bot.py alerts
