name: Economic Calendar Telegram Bot

on:
  schedule:
    # TR = UTC+3; 09:00 TR -> 06:00 UTC
    - cron: "0 6 * * *"      # günlük özet
    - cron: "*/5 * * * *"    # 5 dakikada bir uyarı kontrolü
  workflow_dispatch:
    inputs:
      force:
        description: "Sessiz saatleri yok say (true/false)"
        required: true
        default: "false"
        type: choice
        options: ["false","true"]

jobs:
  # --- Zamanlanmış işler ---
  daily_summary_scheduled:
    if: github.event_name == 'schedule' && github.event.schedule == '0 6 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_calendar_bot.py summary

  half_hour_alerts_scheduled:
    if: github.event_name == 'schedule' && github.event.schedule == '*/5 * * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_calendar_bot.py alerts

  # --- Manuel tetikleme: İKİSİ BİRDEN çalışsın ---
  manual_summary:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_RUN: ${{ github.event.inputs.force }}
        run: python send_calendar_bot.py summary

  manual_alerts:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_RUN: ${{ github.event.inputs.force }}
        run: python send_calendar_bot.py alerts
